name: WhereDaFlock
options:
  bundleIdPrefix: com.wheredaflock
  deploymentTarget:
    iOS: "17.0"
    watchOS: "10.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"

targets:
  WhereDaFlock:
    type: application
    platform: iOS
    sources:
      - path: WhereDaFlock
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wheredaflock.app
        INFOPLIST_FILE: WhereDaFlock/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_BITCODE: NO

  WhereDaFlockTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: WhereDaFlockTests
    dependencies:
      - target: WhereDaFlock
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wheredaflock.tests
        GENERATE_INFOPLIST_FILE: YES

  WhereDaFlockUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: WhereDaFlockUITests
    dependencies:
      - target: WhereDaFlock
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wheredaflock.uitests
        GENERATE_INFOPLIST_FILE: YES

  WhereDaFlockWidgets:
    type: app-extension
    platform: iOS
    sources:
      - path: WhereDaFlockWidgets
    dependencies:
      - target: WhereDaFlock
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wheredaflock.app.widgets
        GENERATE_INFOPLIST_FILE: YES

  WhereDaFlockWatch:
    type: application
    platform: watchOS
    sources:
      - path: WhereDaFlockWatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.wheredaflock.app.watchkitapp
        GENERATE_INFOPLIST_FILE: YES
